# Generated by Django 5.1 on 2024-08-30 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('small', 'Piccola'), ('medium', 'Media'), ('large', 'Grande')], max_length=10, unique=True)),
                ('camere_totali', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=50)),
                ('numero_posti_letto', models.IntegerField(default=1)),
                ('prezzo_per_notte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('immagine1', models.ImageField(blank=True, null=True, upload_to='camere/')),
                ('immagine2', models.ImageField(blank=True, null=True, upload_to='camere/')),
                ('immagine3', models.ImageField(blank=True, null=True, upload_to='camere/')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camere',
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.CharField(choices=[('antipasti', 'Antipasti'), ('primi', 'Primi'), ('secondi', 'Secondi'), ('contorni', 'Contorni'), ('dolci', 'Dolci'), ('bevande', 'Bevande')], max_length=20)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='menu/')),
            ],
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('posti', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tavolo',
                'verbose_name_plural': 'Tavoli',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commento', models.TextField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
            },
        ),
        migrations.CreateModel(
            name='TavoloBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('orario_arrivo', models.TimeField()),
                ('tipo_pasto', models.CharField(choices=[('pranzo', 'Pranzo'), ('cena', 'Cena')], max_length=15)),
                ('numero_persone', models.IntegerField()),
                ('numero_telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tavolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prenotazione Tavolo',
                'verbose_name_plural': 'Prenotazioni Tavoli',
            },
        ),
    ]
