# Generated by Django 5.1 on 2024-08-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavolobooking',
            options={'ordering': ['data'], 'verbose_name': 'Prenotazione Tavolo', 'verbose_name_plural': 'Prenotazioni Tavoli'},
        ),
    ]
