# Generated by Django 5.1 on 2024-08-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Camere'},
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='tavolo',
            options={'verbose_name': 'Tavolo', 'verbose_name_plural': 'Tavoli'},
        ),
    ]
