# Generated by Django 5.1 on 2024-08-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tavolobooking_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='utente',
            new_name='user',
        ),
    ]
