# Generated by Django 5.1 on 2024-08-28 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_camera_options_alter_roombooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='numero_telefono',
            field=models.CharField(default=3311153340, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tavolo',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='TavoloBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('orario_arrivo', models.TimeField()),
                ('tipo_pasto', models.CharField(choices=[('pranzo', 'Pranzo'), ('cena', 'Cena')], max_length=15)),
                ('numero_persone', models.IntegerField()),
                ('numero_telefono', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tavolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prenotazione Tavolo',
                'verbose_name_plural': 'Prenotazioni Tavoli',
            },
        ),
    ]
