# Generated by Django 5.1 on 2024-08-31 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_utente_roombooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recensione',
            old_name='utente',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recensione',
            name='categoria',
            field=models.CharField(choices=[('ristorante', 'Ristorante'), ('albergo', 'Albergo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recensione',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
