# Generated by Django 5.1 on 2024-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_utente_recensione_user_recensione_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='descrizione',
            field=models.TextField(blank=True, default='descrizione'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='tipo',
            field=models.CharField(choices=[('small', 'Piccola'), ('medium', 'Media'), ('large', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='note',
            field=models.TextField(blank=True, default='descrizione'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tavolobooking',
            name='note',
            field=models.TextField(blank=True, default='descrizione'),
            preserve_default=False,
        ),
    ]
