# Generated by Django 5.1 on 2024-08-26 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_immagini_camera_immagini1_camera_immagini2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='categoria',
            field=models.CharField(choices=[('antipasti', 'Antipasti'), ('primi', 'Primi'), ('secondi', 'Secondi'), ('contorni', 'Contorni'), ('dolci', 'Dolci'), ('bevande', 'Bevande')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
