# Generated by Django 5.1 on 2024-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_camera_descrizione_alter_camera_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Articolo del Menu', 'verbose_name_plural': 'Articoli del Menu'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name': 'Recensione', 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
