# Generated by Django 5.1 on 2024-09-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_menuitem_options_alter_recensione_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Core',
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['start_date'], 'verbose_name': 'Prenotazione Camera', 'verbose_name_plural': 'Prenotazioni Camere'},
        ),
    ]
